spring:
  application:
    name: '@project.name@'
  devtools:
    livereload:
      enabled: true
  flyway:
    enabled: true
    out-of-order: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        types:
          print:
            banner: false
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/parking?reWriteBatchedInserts=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jackson:
    default-property-inclusion: non_null
    locale: pt_BR
    time-zone: America/Sao_Paulo
    serialization:
      write-dates-as-timestamps: false
      indent_output: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
      fail_on_null_for_primitives: false