package com.carjunior.manageparking.domain.entity.enums;

public enum Permission {

    PARKING_CREATE,
    PARKING_UPDATE,
    PARKING_LIST,
    PARKING_DETAIL,

    VEHICLE_CREATE,
    VEHICLE_UPDATE,
    VEHICLE_LIST,
    VEHICLE_DETAIL,

    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_LIST,
    ROLE_DETAIL,

    USER_CREATE,
    USER_UPDATE,
    USER_LIST,
    USER_DETAIL,

    PARKING_CONTROL_VEHICLE_ENTRANCE,
    PARKING_CONTROL_FINISH_VEHICLE_ENTRANCE,
    PARKING_CONTROL_SUMMARY,
    PARKING_CONTROL_SUMMARY_PER_HOUR;

}